### ISSUE TITLE
setting logical_asset_filter configuration crashed under 0.9.8 and Rails 4.2.1

### ISSUE THREAD

**Issue by gtd** [jwhitley/requirejs-rails#235] opened 2015-06-13 21:34 UTC
I am in the process of upgrade an app from Rails 3.2 to 4.2.  My jquery-rails is locked to 0.9.5 and loading works.  If I update to 0.9.8, then I get the following error:

    /Users/gtd/repo/config/application.rb:160:in `<class:Application>': undefined method `+' for #<Mubi::Application:0x007fc9335940f8> (NoMethodError)

This corresponds to this line in application.rb:

    config.requirejs.logical_asset_filter += [/\.hbs$/]

**Comment by jezstephens** [comment] 2015-06-20 17:41
Duplicate of #229

**Comment by carsomyr** [comment] 2015-06-22 01:22
@gtd See previous issue.

**Closed** 2015-06-22 01:22 UTC
